// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCghCWCk-pZvX8R7Rk4wN5Vi1QjRbOQE',
    appId: '1:348528851615:web:ad156a1cb4c7d887db40aa',
    messagingSenderId: '348528851615',
    projectId: 'esavior',
    authDomain: 'esavior.firebaseapp.com',
    storageBucket: 'esavior.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_jKL0wzCk0kZykfrjHHuNlAKGfX4Hzco',
    appId: '1:348528851615:android:42984903a8e8aeb1db40aa',
    messagingSenderId: '348528851615',
    projectId: 'esavior',
    storageBucket: 'esavior.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47lMbdqcddZQGq14SX4CtLE_VHzFjzN4',
    appId: '1:348528851615:ios:1f2c6de4a0e72833db40aa',
    messagingSenderId: '348528851615',
    projectId: 'esavior',
    storageBucket: 'esavior.appspot.com',
    iosBundleId: 'com.example.eSavior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47lMbdqcddZQGq14SX4CtLE_VHzFjzN4',
    appId: '1:348528851615:ios:1f2c6de4a0e72833db40aa',
    messagingSenderId: '348528851615',
    projectId: 'esavior',
    storageBucket: 'esavior.appspot.com',
    iosBundleId: 'com.example.eSavior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkCghCWCk-pZvX8R7Rk4wN5Vi1QjRbOQE',
    appId: '1:348528851615:web:97fa712416b5fb72db40aa',
    messagingSenderId: '348528851615',
    projectId: 'esavior',
    authDomain: 'esavior.firebaseapp.com',
    storageBucket: 'esavior.appspot.com',
  );
}
